const express=require('express')
const addMarks = require('./fetchMarks')
const addNewStudent = require('./addNewStudent')
const addNewSubject = require('./addNewSubject')
const displaySubjects=require('./displaySubjects')
const dashboard=require('./dashboard')
const verifyJwt=require('./verifyJwt')
const fetchMarks = require('./fetchMarks')
const displayStudents = require('./displayStudents')
const updateMarks = require('./updateMarks')
const studentMarks = require('./studentMarks')
const router=express.Router()

router.get('/dashboard',dashboard)
router.post('/addNewStudent',addNewStudent)
router.post('/addNewSubject',addNewSubject)
router.post('/addMarks',addMarks)
router.get('/displaySubjects',displaySubjects)
router.post('/verifyJwt',verifyJwt)
router.post('/fetchMarks',fetchMarks)
router.get('/displayStudents',displayStudents)
router.post('/updateMarks',updateMarks)
router.post('/studentMarks',studentMarks)
//router.post('/signup',signup_user)

module.exports=router